### ISSUE TITLE
Style for verbs.dart

### ISSUE THREAD

**Issue by mattdbr** [adaojunior/english-verbs#8]
Noticed that you switch styles for the lists in verbs.dart:

```
{"1": "blow", "2": "blown", "3": "blowing", "4": "blew", "5": "blows"},
```

and 
      {
      "1": "blush",
      "2": "blushed",
      "3": "blushing",
      "4": "blushed",
      "5": "blushes"
    },

Which of these is the way you want future contributers to send PRs in? Also do you accept colloquial verbs?

**Comment by adaojunior** [comment]
It used to be the second one, but since I run `dartfmt` it changed the ones that fit in one line and x number of characters. I think I may format it back to what it was before `dartfmt`, but for now you can send a PR with both ways and I'm fine.
And also I'm a ESL student, I don't know what you want to be done with colloquial verbs.
I'd be glad you you could explain it to me, and also explain your vision on why it would be helpful for other students.

Thanks

**Comment by mattdbr** [comment]
Closing. For the moment I won't include colloquial verbs.
